name: chefsandmeals_customer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  syncfusion_flutter_datepicker: ^19.4.50
  flutter_datetime_picker: ^1.5.1
  sms_autofill:
  velocity_x: ^3.4.0
  get: ^4.6.1
  shared_preferences: ^2.0.13
  flutter_launcher_icons:
  page_transition: ^2.0.5
  lazy_load_scrollview: ^1.3.0
  #path: ^1.8.0
  path_provider: ^2.0.8
  image: ^3.1.1
  image_gallery_saver: ^1.7.1
  dio: ^4.0.4
  share: ^2.0.4
  carousel_slider: ^4.0.0
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.3.0
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.0
  geolocator: ^8.1.1
  shimmer: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  flutter_spinkit: ^5.1.0
  googleapis_auth: ^1.3.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.2.3
  change_app_package_name: ^1.0.0
  fancy_shimmer_image: ^2.0.1+1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.18
  intl: ^0.17.0
  image_picker: ^0.8.4+7
  contacts_service: ^0.6.3
  permission_handler: ^8.3.0
  square_in_app_payments: ^1.7.2
  flutter_time_picker_spinner: ^2.0.0
  expandable: ^5.0.1
  fdottedline:
    git:
      url: https://github.com/Taskulu/fdottedline.git
      ref: null-safety
  location: ^4.3.0
  qr_flutter: ^4.0.0
  #firebase_messaging: ^11.2.8

  the_apple_sign_in: ^1.1.1
#  sign_in_apple: ^2.0.0
  webview_flutter: ^3.0.1
  flutter_switch: ^0.3.2
  dots_indicator: ^2.1.0
  fluttertoast: ^8.0.9
  awesome_dialog: ^2.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  assets:
    - assets/
    - assets/launcher/
    - assets/icons/
    - assets/images/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  image_path: "assets/launcher/launcher_icon.png"
  android: true
  ios: true