import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSq72bkY5l8Jd6fyAXvh6JodeRWETW-rk',
    appId: '1:172536347629:web:e791b3e4090ce5e707c5e4',
    messagingSenderId: '172536347629',
    projectId: 'prime-granite-331217',
    authDomain: 'prime-granite-331217.firebaseapp.com',
    storageBucket: 'prime-granite-331217.appspot.com',
    measurementId: 'G-3QSYN13133',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtU2Yt3vckzyjODt8aHPC_lat7QeVEx0Y',
    appId: '1:172536347629:android:61dc70fc52e1782d07c5e4',
    messagingSenderId: '172536347629',
    projectId: 'prime-granite-331217',
    storageBucket: 'prime-granite-331217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfleU6whT9YeSnzXdKN1rAxJpmaYFN554',
    appId: '1:172536347629:ios:55c9cd9ee4bd81e707c5e4',
    messagingSenderId: '172536347629',
    projectId: 'prime-granite-331217',
    storageBucket: 'prime-granite-331217.appspot.com',
    androidClientId:
        '172536347629-e4595g0amfasj18280aduqi7pdu4m43a.apps.googleusercontent.com',
    iosClientId:
        '172536347629-4ite0ju1jugbolts6ek0kkh0mpii8kvp.apps.googleusercontent.com',
    iosBundleId: 'com.chefsnmeals.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfleU6whT9YeSnzXdKN1rAxJpmaYFN554',
    appId: '1:172536347629:ios:55c9cd9ee4bd81e707c5e4',
    messagingSenderId: '172536347629',
    projectId: 'prime-granite-331217',
    storageBucket: 'prime-granite-331217.appspot.com',
    androidClientId:
        '172536347629-e4595g0amfasj18280aduqi7pdu4m43a.apps.googleusercontent.com',
    iosClientId:
        '172536347629-4ite0ju1jugbolts6ek0kkh0mpii8kvp.apps.googleusercontent.com',
    iosBundleId: 'com.chefsnmeals.customer',
  );
}
